app:
  name: "music-service"
  port: "8080"

db:
  host: "postgres"
  port: "5432"
  username: "sonya"
  password: "1234"
  name: "music_service"
  sslmode: "disable" 

storage:
  tracks_dir: "./storage/tracks"
  max_file_size_mb: 20
  allowed_types:
    - "audio/mpeg"
    - "audio/mp3" 